export const ADD_STUDENT = "ADD_STUDENT";
export const SELECT_STUDENT = "SELECT_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const SEARCH_STUDENT = "SEARCH_STUDENT";
export const RESET_FORM = "RESET_FORM";